### ISSUE TITLE
Testing the functionality of the Engine and Creator classes

### ISSUE THREAD

**Issue by mmunozba** [nfode/stupro_toscana_vorprojekt#18]
To ensure the correct functionality of the Engine classes, all methods should be tested with an example topology.

Progress:
- [x] creating an example topology (as a data model)
- [x] create() method
  - [x] sorting methods in the Creator class
- [x] start() method
- [x] stop() method

**Comment by JensMueller2709** [comment]
i wrote some test cases for the creator-classes
we have to implement the ssh-connection to do further tests with the create-method

**Comment by JensMueller2709** [comment]
works
