### ISSUE TITLE
Remove all .iml files and the .idea folder from git

### ISSUE THREAD

**Issue by nfode** [nfode/stupro_toscana_vorprojekt#19]
The .iml files and the .idea folder are not necessary to configure IntelliJ, the IDE generates these files out of the pom.xml. So theres no need for them to be in the repo.
To remove these files from git do the following steps.

1. Get the new .gitignore from master:
you can run `git checkout --patch master .gitignore` to get the new file, or just copy and paste to your branch
2. remove the files from git:
`git rm -r --cached .idea`
`git rm -r --cached *.iml`
this wont remove them from you hard drive only from git
3. stage,commit and push to your branch

thx!

**Comment by sahamnadeem** [comment]
fatal: pathspec '.idea' did not match any files

**Comment by c-mueller** [comment]
?

**Comment by Kazeshini94** [comment]
thanks mate 💯  this drove me crazy and i just started out with git a few days ago  🥇
