### ISSUE TITLE
Implement model interpreter

### ISSUE THREAD

**Issue by mmunozba** [nfode/stupro_toscana_vorprojekt#7]
The engine needs to be able to interpret the data model created by the XML parser in order to generate the sequence of deployment operations. This is done by iterating through the nodes and relationships in the data model and determining the dependencies.

- [x] enable interpretation of TOSCAlite models
- [x] create a method to sort Nodes based on parent-child relationships
- [x] integrate the sorted Node list into the create(), start() and stop() methods

**Comment by JensMueller2709** [comment]
in the creator class we sort the nodes by ascending order, so machine-node comes first and so on.
the result is saved in queues. for the start-method we can use the same queue in ascending order. for the stop-method we have to change the direction of the queue which means stop the last element of the queue at first.
